// <auto-generated />
using System;
using EF_CodeFirst.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_CodeFirst.Migrations
{
    [DbContext(typeof(CollegeContext))]
    [Migration("20220401081456_SeedingDb")]
    partial class SeedingDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.Property<int>("GradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GradeId"), 1L, 1);

                    b.Property<string>("GradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("GradeId");

                    b.HasIndex("StudentId");

                    b.ToTable("Grades");

                    b.HasData(
                        new
                        {
                            GradeId = 1,
                            GradeName = "Dovoljan",
                            Section = "Modul 1",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 2,
                            GradeName = "Nedovoljan",
                            Section = "Modul 1",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 3,
                            GradeName = "Odličan",
                            Section = "Modul 2",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 4,
                            GradeName = "Odličan",
                            Section = "Modul 2",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 5,
                            GradeName = "Odličan",
                            Section = "Modul 3",
                            StudentId = 1
                        },
                        new
                        {
                            GradeId = 6,
                            GradeName = "Odličan",
                            Section = "Modul 3",
                            StudentId = 2
                        },
                        new
                        {
                            GradeId = 7,
                            GradeName = "Odličan",
                            Section = "Modul 1",
                            StudentId = 2
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Student", b =>
                {
                    b.Property<int>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentID"), 1L, 1);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nchar(20)");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("StudentID");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentID = 1,
                            DateOfBirth = new DateTime(1988, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 201.5m,
                            StudentName = "Ivan Ivic",
                            Weight = 100.0
                        },
                        new
                        {
                            StudentID = 2,
                            DateOfBirth = new DateTime(1950, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 181.5m,
                            StudentName = "Hrvoje Horvat",
                            Weight = 83.0
                        });
                });

            modelBuilder.Entity("EF_CodeFirst.Models.Grade", b =>
                {
                    b.HasOne("EF_CodeFirst.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
